language: c
sudo: false
cache: ccache
addons:
  apt:
    packages:
      - texinfo
      - cmake
      - libgmp-dev
      - libmpfr-dev
      - libntl-dev

env:
  MAKE="make -j -l8"

os:
  - linux

compiler:
  - gcc

install:
  - mkdir build
  - cd build
  - cmake -G"Unix Makefiles" -DWITH_NTL=yes -DBUILD_TESTING=yes -DCMAKE_BUILD_TYPE=Release ..
  - ${MAKE}
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ldd lib/libflint.so; fi

script:
  - ${MAKE} test
